server:
  port: 20000

spring:
  mvc:
    static-path-pattern: /resources/**
  web:
    resources:
      static-locations: /resources/**
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

holland:
